version: "3"
services:
  api:
    ports:
      - "8080:8080"

  postgres:
    environment:
      - POSTGRES_DB=paymal
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"